#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ AM3D ZIRENE® Uninstall Aroma module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

if [ ! -d "$SYS/vendor" ] || [ -L "$SYS/vendor" ]; then
  safe_mount /vendor
  VEN=/vendor
elif [ -d "$SYS/vendor" ] || [ -L "/vendor" ]; then
  VEN=$SYS/vendor
fi

APP=$SYS/app
ETC=$SYS/etc
VETC=$VEN/etc
PAPP=$SYS/priv-app
DEUTFX=$SYS/lib/soundfx/deuteronomy
PRESETS=$SYS/etc/presets
AM3D=AM3DZirene
AM3DAPK=AM3DZirene.apk
AM3DLIB=libam3daudioenhancement.so
AEC=audio_effects.conf
HTC=htc_audio_effects.conf
AEV=audio_effects_vendor.conf
AOE=audio_offoad_effects.conf

SP=set_perm
SPR=set_perm_recursive

rm -rf $PAPP/$AM3D
rm -rf $PRESETS
rm -f $APP/$AM3DAPK
rm -f $DEUTFX/$AM3DLIB

for CFG in $ETC/$AEC $ETC/$HTC $ETC/$AEV $VETC/$AOE; do

  if [ -f "$CFG" ]; then

  sed -i '/am3daudioenhancement {/,/}/d' $CFG

  fi

done

exit 0
