#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ Arkamys™ Audio Uninstall AROMA module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2;

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

if [ ! -d "$SYS/vendor" ] || [ -L "$SYS/vendor" ]; then
  safe_mount /vendor
  VEN=/vendor
elif [ -d "$SYS/vendor" ] || [ -L "/vendor" ]; then
  VEN=$SYS/vendor
fi

APP=$SYS/app
ETC=$SYS/etc
VETC=$VEN/etc
DEUTFX=$SYS/lib/soundfx/deuteronomy
ARK=ArkamysAudio
ARKAPK=ArkamysAudio.apk
ARKLIB=libarkamys.so
JAR=$SYS/framework/com.arkamysaudio.jar
XML=$SYS/etc/permissions/com.arkamysaudio.xml
AEC=audio_effects.conf
HTC=htc_audio_effects.conf
AEV=audio_effects_vendor.conf
AOE=audio_offload_effects.conf

rm -rf $APP/$ARK
rm -f $APP/$ARKAPK
rm -f $DEUTFX/$ARKLIB
rm -f $JAR
rm -f $XML

for CFG in $ETC/$AEC $ETC/$HTC $ETC/$AEV $VETC/$AOE; do

  if [ -f "$CFG" ]; then

    sed -i '/arkamys {/,/}/d' $CFG
    sed -i '/Arkamysfx {/,/}/d' $CFG

  fi

done

exit 0
