#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ smeejaytee's "Feel the Beats™" ToolBox Uninstall AROMA module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

set_perm() {
 if [ -e $1 ]; then
  chown $2:$3 $1 || exit 1
  chmod $4 $1 || exit 1
  if [ "$5" ]; then
  chcon $5 $1 2>/dev/null
  else
  chcon 'u:object_r:system_file:s0' $1 2>/dev/null
  fi
 fi
}

set_perm_recursive() {
  find $1 -type d 2>/dev/null | while read dir; do
    set_perm $dir $2 $3 $4 $6
  done
  find $1 -type f 2>/dev/null | while read file; do
    set_perm $file $2 $3 $5 $6
  done
}

MOD=core
CUST=custom
BIN=$SYS/bin
ETC=$SYS/etc
LIB=$SYS/lib
SUD=$SYS/su.d
ALSA=$SYS/usr/shared/alsa
NEWPROP=arisesound_setprop
OLDPROP=smeejaytee_setprop
SP=set_perm
SPR=set_perm_recursive

rm -rf $ALSA
rm -rf $ETC/srs
rm -f $ETC/asound.conf
rm -f $BIN/alsa_amixer
rm -f $BIN/alsa_aplay
rm -f $BIN/alsa_ctl
rm -f $BIN/arm-linux-gnueabi-sndfile-resample
rm -f $LIB/libalsa-msm.so
rm -f $LIB/libasound.so
rm -f $LIB/libresample.so
rm -f $LIB/libsamplerate.so
rm -f $LIB/libsndfile.so
rm -f $SUD/$OLDPROP

cd /tmp

mkdir -p $ALSA
mkdir -p $ETC/srs
cp -Rf $MOD/usr/share/alsa/* $ALSA
cp -Rf $CUST/huawei/system/etc/srs/* $ETC/srs
cp -f $MOD/su.d/$NEWPROP $SUD/$NEWPROP
$SPR $ALSA 0 0 0755 0644
$SPR $ETC/srs 0 0 0755 0644
$SP $SUD/$NEWPROP 0 0 0700
restorecon $SUD/$NEWPROP

rm -rf /tmp/core
rm -rf /tmp/custom

exit 0
