#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ AM3D ZIRENE® Aroma module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

if [ ! -d "$SYS/vendor" ] || [ -L "$SYS/vendor" ]; then
  safe_mount /vendor
  VEN=/vendor
elif [ -d "$SYS/vendor" ] || [ -L "/vendor" ]; then
  VEN=$SYS/vendor
fi

if [ -e "$VEN/build.prop" ] && [ ! -e "$SYS/build.prop" ]; then
  BUILDPROP=$VEN/build.prop
elif [ -e "$SYS/build.prop" ] && [ ! -e "$VEN/build.prop" ]; then
  BUILDPROP=$SYS/build.prop
elif [ -e "$SYS/build.prop" ] && [ -e "$VEN/build.prop" ]; then
  if [ $(wc -c < "$SYS/build.prop") -ge $(wc -c < "$VEN/build.prop") ]; then
    BUILDPROP=$SYS/build.prop
  else
    BUILDPROP=$VEN/build.prop
  fi
fi

set_perm() {
 if [ -e $1 ]; then
  chown $2:$3 $1 || exit 1
  chmod $4 $1 || exit 1
  if [ "$5" ]; then
  chcon $5 $1 2>/dev/null
  else
  chcon 'u:object_r:system_file:s0' $1 2>/dev/null
  fi
 fi
}

set_perm_recursive() {
  find $1 -type d 2>/dev/null | while read dir; do
    set_perm $dir $2 $3 $4 $6
  done
  find $1 -type f 2>/dev/null | while read file; do
    set_perm $file $2 $3 $5 $6
  done
}

MOD=am3d
VETC=$VEN/etc
APP=$SYS/app
ETC=$SYS/etc
PAPP=$SYS/priv-app
DEUTFX=$SYS/lib/soundfx/deuteronomy
SUD=$SYS/su.d
PRESETS=$SYS/etc/presets
AM3D=AM3DZirene
AM3DAPK=AM3DZirene.apk
AM3DLIB=libam3daudioenhancement.so
AEC=audio_effects.conf
HTC=htc_audio_effects.conf
AEV=audio_effects_vendor.conf
AOE=audio_offload_effects.conf
SERVER=arisesoundserver
API=$(cat $BUILDPROP | grep "ro.build.version.sdk=" | dd bs=1 skip=21 count=2)
SP=set_perm
SPR=set_perm_recursive

cd /tmp

cp -R $MOD/system/* $SYS
$SPR $PRESETS 0 0 0755 0644
$SP $DEUTFX/$AM3DLIB 0 0 0644
$SP $SUD/permissive 0 0 0700
restorecon $SUD/permissive

if [ "$API" -ge "21" ]; then

  rm -f $SUD/$SERVER
  mkdir -p $PAPP/$AM3D
  cp -f $MOD/$AM3DAPK $PAPP/$AM3D/$AM3DAPK
  cp -f $MOD/permissive $SUD/permissive
  $SPR $PAPP/$AM3D 0 0 0755 0644
  $SP $SUD/permissive 0 0 0700
  restorecon $SUD/permissive

else

  cp -f $MOD/$AM3DAPK $APP/$AM3DAPK
  $SP $APP/$AM3DAPK 0 0 0644

fi

for CFG in $ETC/$AEC $ETC/$HTC $ETC/$AEV $VETC/$AOE; do

  if [ -f "$CFG" ]; then

    sed -i '/am3daudioenhancement {/,/}/d' $CFG
    sed -i 's/^# AM3D | www.am3d.com | Library/# AM3D | www.am3d.com | Library\n\n  am3daudioenhancement {\n    path \/system\/lib\/soundfx\/deuteronomy\/libam3daudioenhancement.so\n  }/g' $CFG
    sed -i 's/^# AM3D | www.am3d.com | Effect/# AM3D | www.am3d.com | Effect\n\n  am3daudioenhancement {\n    library am3daudioenhancement\n    uuid 6723dd80-f0b7-11e0-98a2-0002a5d5c51b\n  }/g' $CFG

  fi

done

rm -rf /tmp/am3d

exit 0
