#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ Dolby Digital Plus™ AROMA module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

if [ ! -d "$SYS/vendor" ] || [ -L "$SYS/vendor" ]; then
  safe_mount /vendor
  VEN=/vendor
elif [ -d "$SYS/vendor" ] || [ -L "/vendor" ]; then
  VEN=$SYS/vendor
fi

if [ -e "$VEN/build.prop" ] && [ ! -e "$SYS/build.prop" ]; then
  BUILDPROP=$VEN/build.prop
elif [ -e "$SYS/build.prop" ] && [ ! -e "$VEN/build.prop" ]; then
  BUILDPROP=$SYS/build.prop
elif [ -e "$SYS/build.prop" ] && [ -e "$VEN/build.prop" ]; then
  if [ $(wc -c < "$SYS/build.prop") -ge $(wc -c < "$VEN/build.prop") ]; then
    BUILDPROP=$SYS/build.prop
  else
    BUILDPROP=$VEN/build.prop
  fi
fi

set_perm() {
 if [ -e $1 ]; then
  chown $2:$3 $1 || exit 1
  chmod $4 $1 || exit 1
  if [ "$5" ]; then
  chcon $5 $1 2>/dev/null
  else
  chcon 'u:object_r:system_file:s0' $1 2>/dev/null
  fi
 fi
}

set_perm_recursive() {
  find $1 -type d 2>/dev/null | while read dir; do
    set_perm $dir $2 $3 $4 $6
  done
  find $1 -type f 2>/dev/null | while read file; do
    set_perm $file $2 $3 $5 $6
  done
}

MOD=ddplus
CUST=custom
VETC=$VEN/etc
ETC=$SYS/etc
LIB=$SYS/lib
PAPP=$SYS/priv-app
SUD=$SYS/su.d
DEUTFX=$SYS/lib/soundfx/deuteronomy
DDPLIB=libdseffect.so
MFX=MusicFX
MFXAPK=MusicFX.apk
AEC=audio_effects.conf
HTC=htc_audio_effects.conf
AEV=audio_effects_vendor.conf
AOE=audio_offload_effects.conf
SERVER=arisesoundserver
API=$(cat $BUILDPROP | grep "ro.build.version.sdk=" | dd bs=1 skip=21 count=2)
SP=set_perm
SPR=set_perm_recursive

cd /tmp

if [ "$API" -lt "23" ]; then

  ui_print " "
  ui_print " "
  ui_print "Unfortunately, Marshmallow is the minimum OS for the Dolby Digital Plus module. However, the Dolby Atmos module is an available option."
  ui_print " "
  ui_print " "

else

  rm -f $SUD/$SERVER
  cp -Rf $MOD/* $SYS
  $SPR $PAPP/Ds 0 0 0755 0644
  $SPR $PAPP/DsUI 0 0 0755 0644
  $SPR $SYS/dolby 0 0 0755 0644
  $SP $DEUTFX/$DDPLIB 0 0 0644
  $SP $LIB/libstagefright_soft_ddpdec.so 0 0 0644
  $SP $SUD/permissive 0 0 0700
  restorecon $SUD/permissive

  if [ ! -d "$PAPP/$MFX" ]; then

    mkdir -p $PAPP/$MFX
    cp -f $CUST/$MFXAPK $PAPP/$MFX/$MFXAPK
    $SPR $PAPP/$MFX 0 0 0755 0644

  fi

  for CFG in $ETC/$AEC $ETC/$HTC $ETC/$AEV $VETC/$AOE; do

    if [ -f "$CFG" ]; then

      sed -i '/ds {/,/}/d' $CFG
      sed -i '/dsplus {/,/}/d' $CFG
      sed -i 's/^# Dolby Laboratories, Inc. | www.dolby.com | Library/# Dolby Laboratories, Inc. | www.dolby.com | Library\n\n  ds {\n    path \/system\/lib\/soundfx\/deuteronomy\/libdseffect.so\n  }/g' $CFG
      sed -i 's/^# Dolby Laboratories, Inc. | www.dolby.com | Effect/# Dolby Laboratories, Inc. | www.dolby.com | Effect\n\n  dsplus {\n    library ds\n    uuid 9d4921da-8225-4f29-aefa-39537a04bcaa\n  }/g' $CFG

    fi

  done

fi

rm -rf /tmp/ddplus
rm -rf /tmp/custom

exit 0
