#!/sbin/sh
#
# ARISE Sound Systems™ @XDA Developers
#
# Deuteronomy™ smeejaytee's "Feel the Beats™" ToolBox AROMA module
#
# www.arisesound.com

OUTFD=/proc/self/fd/$2

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

SLOT=$(for i in $(cat /proc/cmdline); do echo $i | grep slot | dd bs=1 skip=24 2>/dev/null; done)
if [ $SLOT != "" ]; then
    echo "slotnum=$SLOT" > /tmp/slotsel
elif [ $(cat /etc/recovery.fstab 2>/dev/null | grep boot_a) != "" ]; then
    echo "slotnum=_a" > /tmp/slotsel
else
    echo "none" > /tmp/slotsel
fi

safe_mount() {
	IS_MOUNTED=$(cat /proc/mounts | grep "$1")
	if [ "$IS_MOUNTED" ]; then
  mount -o rw,remount $1
 else
  mount $1
	fi
}

safe_mount /system

if [ -d "/system/system" ]; then
  SYS=/system/system
else
  SYS=/system
fi

set_perm() {
 if [ -e $1 ]; then
  chown $2:$3 $1 || exit 1
  chmod $4 $1 || exit 1
  if [ "$5" ]; then
  chcon $5 $1 2>/dev/null
  else
  chcon 'u:object_r:system_file:s0' $1 2>/dev/null
  fi
 fi
}

set_perm_recursive() {
  find $1 -type d 2>/dev/null | while read dir; do
    set_perm $dir $2 $3 $4 $6
  done
  find $1 -type f 2>/dev/null | while read file; do
    set_perm $file $2 $3 $5 $6
  done
}

MOD=ToolBox
BIN=$SYS/bin
ETC=$SYS/etc
LIB=$SYS/lib
SUD=$SYS/su.d
ALSA=$SYS/usr/shared/alsa
OLDPROP=arisesound_setprop
NEWPROP=smeejaytee_setprop
SP=set_perm
SPR=set_perm_recursive

rm -f $SUD/$OLDPROP
rm -f $SUD/smeejaytee*

cd /tmp

cp -Rf smeejaytee/$MOD/* $SYS
cp -Rf smeejaytee/ViPER4Android/* /sdcard/ViPER4Android

$SPR $SRS 0 0 0755 0644
$SPR $ETC/snd_soc_msm 0 0 0755 0644
$SPR $ETC/tfa 0 0 0755 0644
$SPR $SUD 0 0 0700 0700
$SPR $SYS/tools 0 0 0755 0644
$SPR $ALSA 0 0 0755 0644
$SP $BIN/alsa_amixer 0 2000 0755
$SP $BIN/alsa_aplay 0 2000 0755
$SP $BIN/alsa_ctl 0 2000 0755
$SP $BIN/arm-linux-gnueabi-sndfile-resample 0 2000 0755
$SP $ETC/asound.conf 0 0 0644
$SP $ETC/Headset_cal.acdb 0 0 0644
$SP $ETC/sound_mfg.txt 0 0 0644
$SP $ETC/sound_mfg_DMIC.txt 0 0 0644
$SP $HTC 0 0 0644
$SP $LIB/libalsa-msm.so 0 0 0644
$SP $LIB/libasound.so 0 0 0644
$SP $LIB/libharmancorehtc.so 0 0 0644
$SP $LIB/libresample.so 0 0 0644
$SP $LIB/libsamplerate.so 0 0 0644
$SP $LIB/libsndfile.so 0 0 0644
$SP $SYS/disclaimer.prop 0 0 0644
$SP $SUD/$NEWPROP 0 0 0700
restorecon $SUD/$NEWPROP

rm -rf /tmp/ToolBox

exit 0
